import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { Images, Heart, Download, Filter, Sparkles } from 'lucide-react';

export const GalleryView: React.FC = () => {
  const { historyItems, favorites, toggleFavorite } = useApp();
  const [filter, setFilter] = useState<'all' | 'favorites'>('all');
  const [selectedImg, setSelectedImg] = useState<string | null>(null);

  const galleryItems = historyItems
    .filter((item) => filter === 'all' || favorites.includes(item.id))
    .map((item) => ({
      id: item.id,
      url: item.thumbnailUrl,
      title: item.title,
      subtitle: item.subtitle,
      isFav: favorites.includes(item.id),
    }));

  return (
    <div className="min-h-[calc(100vh-4rem)] bg-transparent text-white p-6 overflow-y-auto">
      <div className="max-w-6xl mx-auto space-y-6">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-4">
          <div>
            <div className="flex items-center space-x-2">
              <Images className="w-6 h-6 text-purple-400" />
              <h2 className="text-xl font-bold text-white">Art Gallery</h2>
            </div>
            <p className="text-xs text-slate-400 mt-1">
              Curated artwork collection generated by SDXL-Turbo and analyzed by MobileNetV3
            </p>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={() => setFilter('all')}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold border transition-all ${
                filter === 'all'
                  ? 'bg-purple-950/80 border-purple-500 text-purple-300'
                  : 'bg-slate-900 border-slate-800 text-slate-400'
              }`}
            >
              All Artworks ({historyItems.length})
            </button>

            <button
              onClick={() => setFilter('favorites')}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold border transition-all ${
                filter === 'favorites'
                  ? 'bg-rose-950/80 border-rose-500 text-rose-300'
                  : 'bg-slate-900 border-slate-800 text-slate-400'
              }`}
            >
              Favorites ({favorites.length})
            </button>
          </div>
        </div>

        {/* Gallery Grid */}
        {galleryItems.length > 0 ? (
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
            {galleryItems.map((art) => (
              <div
                key={art.id}
                className="group relative aspect-square rounded-2xl overflow-hidden bg-slate-900 border border-slate-800 hover:border-purple-500/50 shadow-xl transition-all hover:scale-105 cursor-pointer"
              >
                <img
                  src={art.url}
                  alt={art.title}
                  className="w-full h-full object-cover"
                  onClick={() => setSelectedImg(art.url)}
                />

                <div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity p-3 flex flex-col justify-between">
                  <div className="flex justify-end">
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        toggleFavorite(art.id);
                      }}
                      className={`p-2 rounded-full border backdrop-blur-md transition-colors ${
                        art.isFav
                          ? 'bg-rose-500 text-white border-rose-400'
                          : 'bg-slate-950/60 text-slate-300 border-slate-700 hover:text-rose-400'
                      }`}
                    >
                      <Heart className="w-3.5 h-3.5 fill-current" />
                    </button>
                  </div>

                  <div>
                    <h5 className="text-xs font-bold text-white truncate">{art.title}</h5>
                    <p className="text-[10px] text-slate-400 truncate">{art.subtitle}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="p-12 text-center bg-slate-900/40 rounded-3xl border border-slate-800 space-y-3">
            <Sparkles className="w-10 h-10 text-slate-600 mx-auto" />
            <h4 className="text-sm font-bold text-slate-300">Gallery Empty</h4>
            <p className="text-xs text-slate-500">Generate or analyze artworks to populate your studio gallery.</p>
          </div>
        )}

        {/* Modal Lightbox */}
        {selectedImg && (
          <div
            onClick={() => setSelectedImg(null)}
            className="fixed inset-0 z-50 bg-slate-950/90 backdrop-blur-md flex items-center justify-center p-6"
          >
            <div className="max-w-3xl w-full max-h-[85vh] rounded-3xl overflow-hidden bg-slate-900 border border-slate-700 shadow-2xl relative">
              <img src={selectedImg} alt="Enlarged Art" className="w-full h-full object-contain max-h-[80vh]" />
              <div className="absolute top-4 right-4 flex space-x-2">
                <a
                  href={selectedImg}
                  download="artwork.png"
                  onClick={(e) => e.stopPropagation()}
                  className="p-2.5 rounded-full bg-slate-950/80 text-white border border-slate-700"
                >
                  <Download className="w-4 h-4" />
                </a>
              </div>
            </div>
          </div>
        )}

      </div>
    </div>
  );
};
